### ISSUE TITLE
passing position as variable

### ISSUE THREAD

**Issue by gr33my** [kbwood/backgroundpos#1]
Hey there. I'm trying to pass the background position from a variable. Here is the basic idea of what I am trying to do:

``` javascript
background1 = " '-362px 0' ";
background2 = " '-678px 0' ";

$('#bg1').parent().stop().animate({backgroundPosition:background1},200);
$('#bg2').parent().stop().animate({backgroundPosition:background2},300);
```

I receive the following error **"Cannot read property '1' of null ."** It seems like the variable is not being parsed by the pluggin.

To my knowledge this is the syntax to use variables with the default jQuery animate function. Any insight into this would be fantastic!

**Comment by kbwood** [comment]
Don't include the extra quotes:

``` javascript
var background1 = '-362px 0';
var background2 = '-678px 0';
```
